### Assemble anddescribe the created features

In [229]:
import pandas as pd
import numpy as np
import ast

In [230]:
author_feat = pd.read_csv("author_features.csv", index_col=0)
topics_feat = pd.read_csv("topics_features.csv", index_col=0)
other_feat = pd.read_csv("other_features.csv", index_col=0)

In [231]:
author_feat = author_feat.rename(columns={'author_prev_posts_all': 'author_prev_posts_all_time', 
                                          'author_prev_cited_all': 'author_prev_cited_all_time',
                                          'author_citation_rate_all': 'author_citation_rate_all_time'})

In [232]:
author_feat.tail(3)

,author,author_most_frequent_topics,author_prev_posts_all_time,author_prev_posts_month,author_prev_posts_year,author_prev_cited_all_time,author_prev_cited_month,author_prev_cited_year,author_activity_frac_month,author_activity_frac_year,author_citation_rate_all_time,author_citation_rate_month,author_citation_rate_year,author_citation_frac_month,author_citation_frac_year
telegram_index,,,,,,,,,,,,,,,
14323_atel,zylin@astro.ncu.edu.tw,['comet' 'optical' 'solar system object'],4,0,4,4,0,4,0.000000,1.0,1.0,0.0,1.000000,0.000000,1.000000
14943_atel,zylin@astro.ncu.edu.tw,['comet' 'optical' 'solar system object'],5,0,2,4,0,0,0.000000,0.4,0.8,0.0,0.000000,0.000000,0.000000
14967_atel,zylin@astro.ncu.edu.tw,['comet' 'optical' 'solar system object'],6,1,3,6,2,2,0.166667,0.5,1.0,2.0,0.666667,0.333333,0.333333

In [233]:
topics_feat = topics_feat.rename(columns={'topics_prev_posts_all': 'topics_prev_posts_all_time', 
                                          'topics_prev_cited_all_raw': 'topics_prev_cited_all_time_raw', 
                                          'topics_prev_cited_all_weighted': 'topics_prev_cited_all_time_weighted', 
                                          'topics_citation_rate_all_raw': 'topics_citation_rate_all_time_raw',
                                          'topics_citation_rate_all_weighted': 'topics_citation_rate_all_time_weighted'})

topics_feat['topics_weight_coef_all_time'] = topics_feat.topics_prev_cited_all_time_weighted/topics_feat.topics_prev_cited_all_time_raw
topics_feat['topics_weight_coef_year'] = topics_feat.topics_prev_cited_year_weighted/topics_feat.topics_prev_cited_year_raw
topics_feat['topics_weight_coef_month'] = topics_feat.topics_prev_cited_month_weighted/topics_feat.topics_prev_cited_month_raw

In [234]:
topics_feat.tail(3)

,topics,topics_prev_posts_all_time,topics_prev_posts_month,topics_prev_posts_year,topics_prev_cited_all_time_raw,topics_prev_cited_month_raw,topics_prev_cited_year_raw,topics_prev_cited_all_time_weighted,topics_prev_cited_month_weighted,topics_prev_cited_year_weighted,...,topics_citation_frac_year,topics_citation_rate_all_time_weighted,topics_citation_rate_month_weighted,topics_citation_rate_year_weighted,topics_citation_rate_all_time_raw,topics_citation_rate_month_raw,topics_citation_rate_year_raw,topics_weight_coef_all_time,topics_weight_coef_year,topics_weight_coef_month
telegram_index,,,,,,,,,,,,,,,,,,,,,
16035_atel,"['gamma ray', 'gev', 'request for observations...",4922.400000,10.000000,277.600000,15440.200000,12.600000,500.200000,6886.397802,5.598367,191.680316,...,0.032396,1.398992,0.559837,0.690491,3.136722,1.260000,1.801873,0.446004,0.383207,0.444315
16036_atel,"['cataclysmic variable', 'nova', 'transient']",11037.000000,19.333333,523.000000,39242.333333,47.666667,1076.000000,10955.507968,18.755944,254.486625,...,0.027419,0.992616,0.970135,0.486590,3.555525,2.465517,2.057361,0.279176,0.236512,0.393481
16037_atel,"['optical', 'supernovae', 'transient']",18615.666667,20.000000,747.666667,51733.000000,28.333333,1357.333333,7060.352929,7.362609,195.825805,...,0.026237,0.379269,0.368130,0.261916,2.779003,1.416667,1.815426,0.136477,0.144272,0.259857

In [235]:
other_feat = other_feat.rename(columns={'citation_rate_all': 'citation_rate_all_time',
                                       'citation_rate_frac_year': 'year_citation_rate_to_global_ratio',
                                       'citation_rate_frac_month': 'month_citation_rate_to_global_ratio'})

In [236]:
other_feat.tail(3)

,activity_frac_year,activity_frac_month,citation_rate_year,citation_rate_month,citation_frac_year,citation_frac_month,year_citation_rate_to_global_ratio,month_citation_rate_to_global_ratio,citation_rate_all_time,refs_count,telegram_len,month
telegram_index,,,,,,,,,,,,
16035_atel,0.046234,0.001574,1.977599,1.907895,0.031472,0.001034,0.680707,0.656715,2.905212,0,1605,5
16036_atel,0.046254,0.001595,1.976713,1.883117,0.031472,0.001034,0.680416,0.648199,2.905152,8,2244,5
16037_atel,0.045942,0.001264,1.970243,1.032787,0.031158,0.000449,0.678204,0.355509,2.905091,0,1948,5

In [237]:
df = other_feat.join(author_feat.join(topics_feat)).fillna(0)

In [238]:
len(df.columns)

50

### Create new features and remove unnecessary ones. Then describe all of the remaining

In [241]:
# compare the author's citation rate to the global one
df['author_all_time_citation_rate_to_global_ratio'] = df['author_citation_rate_all_time']/df['citation_rate_all_time']
df['author_month_citation_rate_to_global_ratio'] = df['author_citation_rate_month']/df['citation_rate_month']
df['author_year_citation_rate_to_global_ratio'] = df['author_citation_rate_year']/df['citation_rate_year']

In [242]:
# compare the topics' citation rate to the global one (raw)
df['topics_all_time_citation_rate_to_global_ratio'] = df['topics_citation_rate_all_time_raw']/df['citation_rate_all_time']
df['topics_month_citation_rate_to_global_ratio'] = df['topics_citation_rate_month_raw']/df['citation_rate_month']
df['topics_year_citation_rate_to_global_ratio'] = df['topics_citation_rate_year_raw']/df['citation_rate_year']

In [253]:
# columns_to_keep = ['author_all_time_citation_rate_to_global_ratio', 'author_month_citation_rate_to_global_ratio',
#                   'author_year_citation_rate_to_global_ratio', 'topics_all_time_citation_rate_to_global_ratio',
#                   'topics_month_citation_rate_to_global_ratio', 'topics_year_citation_rate_to_global_ratio',
#                   'year_citation_rate_to_global_ratio', 'month_citation_rate_to_global_ratio', 'topics_activity_frac_month', 
#                   'topics_activity_frac_year', 'author_activity_frac_month', 'author_activity_frac_year', 
#                   'author_citation_rate_month', 'author_citation_rate_year', 'author_citation_rate_all_time',
#                   'topics_citation_rate_month_raw', 'topics_citation_rate_year_raw', 'topics_citation_rate_all_time_raw',
#                   'topics_weight_coef_all_time', 'topics_weight_coef_year', 'topics_weight_coef_month',
#                   'telegram_len', 'refs_count', 'month']

columns_to_keep = ['refs_count', 'telegram_len', 'month',
'month_citation_rate_to_global_ratio', 'year_citation_rate_to_global_ratio',
'author_all_time_citation_rate_to_global_ratio', 'author_year_citation_rate_to_global_ratio', 'author_month_citation_rate_to_global_ratio',
'author_activity_frac_year', 'author_activity_frac_month',
'topics_all_time_citation_rate_to_global_ratio', 'topics_year_citation_rate_to_global_ratio', 'topics_month_citation_rate_to_global_ratio',
'topics_activity_frac_year', 'topics_activity_frac_month',
'topics_weight_coef_all_time', 'topics_weight_coef_year', 'topics_weight_coef_month']

In [254]:
feature_df = df[[*columns_to_keep]].fillna(0)

In [255]:
feature_df.head()

,refs_count,telegram_len,month,month_citation_rate_to_global_ratio,year_citation_rate_to_global_ratio,author_all_time_citation_rate_to_global_ratio,author_year_citation_rate_to_global_ratio,author_month_citation_rate_to_global_ratio,author_activity_frac_year,author_activity_frac_month,topics_all_time_citation_rate_to_global_ratio,topics_year_citation_rate_to_global_ratio,topics_month_citation_rate_to_global_ratio,topics_activity_frac_year,topics_activity_frac_month,topics_weight_coef_all_time,topics_weight_coef_year,topics_weight_coef_month
telegram_index,,,,,,,,,,,,,,,,,,
3_atel,0,1010,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2_atel,0,907,12,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4_atel,0,3607,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
5_atel,0,1509,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6_atel,0,427,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [256]:
feature_df.tail()

,refs_count,telegram_len,month,month_citation_rate_to_global_ratio,year_citation_rate_to_global_ratio,author_all_time_citation_rate_to_global_ratio,author_year_citation_rate_to_global_ratio,author_month_citation_rate_to_global_ratio,author_activity_frac_year,author_activity_frac_month,topics_all_time_citation_rate_to_global_ratio,topics_year_citation_rate_to_global_ratio,topics_month_citation_rate_to_global_ratio,topics_activity_frac_year,topics_activity_frac_month,topics_weight_coef_all_time,topics_weight_coef_year,topics_weight_coef_month
telegram_index,,,,,,,,,,,,,,,,,,
16033_atel,2,1808,5,0.621230,0.685940,0.430243,0.167262,0.000000,0.750000,0.250000,1.039836,0.989255,0.742432,0.058607,0.002090,0.871856,0.794790,0.959072
16034_atel,0,582,5,0.665457,0.680998,0.000000,0.000000,0.000000,0.750000,0.000000,0.745930,0.709567,1.097561,0.032785,0.001444,0.181668,0.219660,0.228022
16035_atel,0,1605,5,0.656715,0.680707,0.000000,0.000000,0.000000,1.000000,0.000000,1.079688,0.911142,0.660414,0.056395,0.002032,0.446004,0.383207,0.444315
16036_atel,8,2244,5,0.648199,0.680416,2.846403,1.138253,1.858621,0.076923,0.038462,1.223869,1.040799,1.309275,0.047386,0.001752,0.279176,0.236512,0.393481
16037_atel,0,1948,5,0.355509,0.678204,0.833785,0.676735,0.000000,0.066667,0.000000,0.956598,0.921422,1.371693,0.040163,0.001074,0.136477,0.144272,0.259857

In [257]:
feature_df.columns.to_list()

['refs_count',
 'telegram_len',
 'month',
 'month_citation_rate_to_global_ratio',
 'year_citation_rate_to_global_ratio',
 'author_all_time_citation_rate_to_global_ratio',
 'author_year_citation_rate_to_global_ratio',
 'author_month_citation_rate_to_global_ratio',
 'author_activity_frac_year',
 'author_activity_frac_month',
 'topics_all_time_citation_rate_to_global_ratio',
 'topics_year_citation_rate_to_global_ratio',
 'topics_month_citation_rate_to_global_ratio',
 'topics_activity_frac_year',
 'topics_activity_frac_month',
 'topics_weight_coef_all_time',
 'topics_weight_coef_year',
 'topics_weight_coef_month']

### Features description:

`refs_count : int` - represents the count of references and citations to other posts included in the telegram body. A higher value suggests that the post is more comprehensive and supported by a significant amount of evidence from external sources.

`telegram_len: int` - the length of the telegram body. The longer length might indicate more substantial observations.

`month: int [1-12]` - the number of the month when observations took place. Regarding to the data analysis we made before, some monthes (June, October) get more citations than the others (December, July).

#### Time-series features (each feature is calculated with respect to the time and never considers the target values from the current observation):
$Note$: by the `year` I mean the previous 365 days, by the `month` - the previous 30 days. Not the calendar month / year.

#### general features:
`month_citation_rate_to_global_ratio: float` -  the average number of citations this month divided by the global average number of citations, reflects the relative interest in recent posts. A higher value of this metric (above 1) suggests an increasing level of interest in the posts made during the current month compared to the overall average citation rate.

`year_citation_rate_to_global_ratio: float` - calculated as the average number of citations during the current year period divided by the global average number of citations. A higher value of this metric (above 1) suggests a growing level of interest in posts made thru the current year.

#### author-based features:

`author_all_time_citation_rate_to_global_ratio: float` - calculated as the average number of citations received by this author(s)' all previous publications divided by the global average number of citations. A value greater than 1 indicates that the author may be relatively more popular or well-known compared to other authors.

`author_year_citation_rate_to_global_ratio: float` - calculated as the average number of citations received by the author's posts during the current year and dividing it by the global average number of citations during the same period.

`author_month_citation_rate_to_global_ratio: float` - calculated as the average number of citations received by the author's posts during the current month and dividing it by the global average number of citations during the same period.

`author_activity_frac_year: float` - the ratio of the number of posts by the author during the current year to the total number of posts by this author. A lower value (minimum of 0) indicates that this is the author's first post in the current year, suggesting limited activity. A higher value (maximum of 1) indicates that all of the author's activity occurred in the current year, suggesting that the author may be relatively new to the field or have a focused presence within a specific time frame.

`author_activity_frac_month: float` - the ratio of the number of posts by the author during the current month to the total number of posts by this author. Same as the feature mentioned above but for the month time period.

#### topics-based features:

`topics_all_time_citation_rate_to_global_ratio: float` - computed as the average number of citations received by all previous publications that share the same topics as the current one, divided by the global average number of citations. A value greater than 1 suggests that these specific topics, in combination, have a higher level of interest and citation compared to other topics. It indicates that publications within these topics tend to receive more attention and citations in general.

`topics_year_citation_rate_to_global_ratio: float` - computed as the average number of citations received by previous publications posted this year that share the same topics as the current one, divided by this year global average number of citations. A value greater than 1 suggests that these specific topics have a higher level of interest during the current year than the other topics.

`topics_month_citation_rate_to_global_ratio: float` - computed as the average number of citations received by previous publications posted this month that share the same topics as the current one, divided by this month global average number of citations.  A value greater than 1 suggests that these specific topics have a higher level of interest during the current month than the other topics.

`topics_activity_frac_year` - the ratio of the number of posts with the same topics during the current year to the total number of posts with these topics. A lower value (minimum of 0) indicates that these topics are not being actively disscussed this year. A higher value (maximum of 1) indicates that most of these topics' related posts occurred in the current year, suggesting that these topics might either be more common for a specific time frame or they are getting more popular recently. 

`topics_activity_frac_month` - same as the feature mentioned above but for the month time period.

`topics_weight_coef_all_time: float` - the weigh coefficient of the topics which takes into the consideration their frequency during the whole time. For each topic we calculate it's relative importance (weight) as:
$$ 
\frac{1}{number\_of\_obseravtions\_with\_this\_topic} * \frac{total\_number\_of\_observations}{number\_of\_unique\_topics}
$$

By applying weights to the citation rates of the topics, we can highlight the less frequent topics by normalizing their citation rates based on their respective weights. For example, topics such as 'transient' or 'optical' are commonly observed in many posts and therefore have weights of 0.1 and 0.2, while the topic 'meteor' is rare and has a weight of 400. The overall weight coefficient is calculated by dividing the raw citations by the weighted citations. A higher value indicates the presence of rare topics.

`topics_weight_coef_year`  - represents the topics weights computed using the mentioned above approach but within a yearly time window. A higher value indicates the presence of topics that are observed less frequently compared to others within this year.

`topics_weight_coef_month` - represents the topics weights computed using the same approach but within a monthly time window. A higher value indicates the presence of topics that are observed less frequently compared to others within this month.

In [258]:
feature_df.to_csv("features.csv", index=True)

In [259]:
feature_df.shape

(48279, 18)