In [1]:
import pandas as pd

In [17]:
df_features = pd.read_csv("../feature_eng/features.csv", index_col=0)
df_doc_vec = pd.read_csv("../doc2vec/doc_vectors.csv", index_col=0)
df_topics_vec = pd.read_csv('../topics/topics_vectors/topics_floret_128.csv', index_col=0)
df_ner_vec = pd.read_csv("../ner/ent_vectors/ent_floret_128.csv", index_col=0)

In [18]:
doc_vec_rename = {c: f'doc_vec_{c}' for c in df_doc_vec.columns}
topics_rename = {c: f'topics_{c}' for c in df_topics_vec.columns}
ner_rename = {c: f'ner_{c}' for c in df_ner_vec.columns}

In [19]:
df_doc_vec = df_doc_vec.rename(columns=doc_vec_rename)
df_topics_vec = df_topics_vec.rename(columns=topics_rename)
df_ner_vec = df_ner_vec.rename(columns=ner_rename)

In [20]:
df = df_features.join(df_doc_vec).join(df_topics_vec).join(df_ner_vec)

In [21]:
df.head()

,refs_count,telegram_len,month,month_citation_rate_to_global_ratio,year_citation_rate_to_global_ratio,author_all_time_citation_rate_to_global_ratio,author_year_citation_rate_to_global_ratio,author_month_citation_rate_to_global_ratio,author_activity_frac_year,author_activity_frac_month,...,ner_246,ner_247,ner_248,ner_249,ner_250,ner_251,ner_252,ner_253,ner_254,ner_255
telegram_index,,,,,,,,,,,,,,,,,,,,,
3_atel,0,1010,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.665767,2.601700,-1.637177,-1.036830,0.364245,1.445063,0.833967,2.841267,-2.536283,0.211777
2_atel,0,907,12,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-4.171000,0.963690,-0.135300,-1.626400,1.131600,0.922140,-0.832150,0.953610,-2.339500,4.451700
4_atel,0,3607,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-4.171000,0.963690,-0.135300,-1.626400,1.131600,0.922140,-0.832150,0.953610,-2.339500,4.451700
5_atel,0,1509,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-3.614550,0.216543,-0.777000,-1.012407,0.580325,0.903885,-0.527262,0.909035,-2.082050,2.950850
6_atel,0,427,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-3.683900,0.738540,-1.723400,-0.424600,-0.223810,1.120200,-0.117950,2.520900,-2.457300,-0.342590

In [22]:
df.to_csv("train_data.csv", index=True)